# use "yapm install ." if you're installing this from git repository

name: json5-utils
version: 0.2.1
description: JSON and JSON5 parsers done right

author:
  name: Alex Kocharin
  email: alex@kocharin.ru
 
repository:
  type: git
  url: git://github.com/rlidwka/json5-utils

bugs:
  url: https://github.com/rlidwka/json5-utils/issues

main: parse.js

scripts:
  test: 'node test/test.js'

keywords:
  - json
  - json5
  - parser

license: WTFPL

