name: jju_demo

version: 0.0.1

author:
  name: Alex Kocharin
  email: alex@kocharin.ru

repository:
  type: git
  url: git://github.com/rlidwka/jju

devDependencies:
  browserify: '*'
  jade: '*'
  jju: '*'
  marked: '*'

license:
  type: WTFPL
  url: http://www.wtfpl.net/txt/copying/

